name: Build release image

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Look around
      run: env
    - name: Build image
      run: docker build . --pull -t docker.pkg.github.com/humppa/sup/sup:$(date +%F)
      ###: docker push docker.pkg.github.com/humppa/sup/sup:$(date +%F)
