name: Build release image

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build image
      run: docker build . --pull -t humppa:$(date +%F)
